### ISSUE TITLE
请教一下模板的使用问题

### ISSUE THREAD

**Issue by NanFeng683** [chianjin/outline-of-mechanics#1]
您好，我是一名在校非计算机专业大学生，粗略学习了LateX的一些知识，想要将一些书籍电子化，恰逢在Github上看到了您对《力学概论》的电子化处理，并热心的公布了TeX源代码，便想借用一下。但在下载完使用时，我遇到了一些问题，一些命令被识别为无效，您的源码也无法直接利用TeXstudio进行编译查看。我本人对LaTeX的学习并不够深，很难搞清楚问题的所在，故希望您给一个联系方式来询问一下解决方案，期待您的垂询

**Comment by NanFeng683** [comment]
> 您好，我是一名在校非计算机专业大学生，粗略学习了LateX的一些知识，想要将一些书籍电子化，恰逢在Github上看到了您对《力学概论》的电子化处理，并热心的公布了TeX源代码，便想借用一下。但在下载完使用时，我遇到了一些问题，一些命令被识别为无效，您的源码也无法直接利用TeXstudio进行编译查看。我本人对LaTeX的学习并不够深，很难搞清楚问题的所在，故希望您给一个联系方式来询问一下解决方案，期待您的垂询

**Comment by chianjin** [comment]
微信 w1280543，欢迎咨询
