### ISSUE TITLE
一个图片的排版问题以及一个新的建议。

### ISSUE THREAD

**Issue by Zhangqq** [chianjin/outline-of-mechanics#13]
第360-361页的图片12.13 引力的非均匀性 被遮住了半幅。另外，我看到现在的翻译书籍往往在页的左右边栏上标记原书的页码，如果参考这样的办法，新书的排版本身可以不用严格沿用旧版的分页，只需在边栏或页脚标注原版页面即可，即可以使用旧版的页码来使用新书。

**Comment by chianjin** [comment]
已修正
