### ISSUE TITLE
图 4.7、6.7 和公式 10.3.9、10.4.3、11.5.3 排版位置问题

### ISSUE THREAD

**Issue by Ming-Hua** [chianjin/outline-of-mechanics#16]
在上一个版本（20230705，这周的新改动还没看）生成的 PDF 中，图 4.7 的题注和下方的正文重叠（原书页码 133 页），公式 11.5.3 的第一行和上方正文重叠（原书页码 321 页）。

我 LaTeX 知识有限，又不太看得懂本书这种目标为仿照原书的排版方式，就不自己改了，只报告个 issue。

**Comment by Ming-Hua** [comment]
还有公式 10.3.9 和 10.4.3（均在原书页码 287 页）也有相同的和上方正文重叠的问题。

**Comment by Ming-Hua** [comment]
第 165 页的图 6.7 也有题注和下方正文重叠的问题。

**Comment by chianjin** [comment]
重叠问题已经做了修正，尚未对照原书调整内容位置。
