### ISSUE TITLE
建议把pdf文件放在github release里而不是git管理

### ISSUE THREAD

**Issue by lingr7** [chianjin/outline-of-mechanics#3]
二进制文件用git管理很。。不方便。会导致git仓库本身的大小极速膨胀。
我用tex排了一本红楼梦。。算和这种仓库有点缘分，哈哈，有点同道中人的感觉。

**Comment by chianjin** [comment]
主要是这种重排的PDF，不好定义 Tag 和版本。生成的 PDF 文件也就 3M 多一点，不大，就放在仓库里了。

**Comment by chianjin** [comment]
接受建议
